import type { DemoConsoleData } from "@/lib/view-models/types";

const demoConsoleData: DemoConsoleData = {
  now: "2026-04-20T12:00:00.000Z",
  workspaces: [
    {
      id: "atlas-core",
      name: "Atlas 核心区",
      description: "编排提案、审批和回放流水线的主工作区。",
      zone: "CN-SH / 控制区",
      health: "warning",
      owners: ["张薇", "徐澈", "李澄"],
      projectCount: 12,
      throughput: 1840,
      successRate: 0.96,
      tags: ["核心", "审批", "时间线"],
      focus: "审批回路存在串行等待",
    },
    {
      id: "relay-labs",
      name: "Relay 实验区",
      description: "用于策略实验、影子运行和新节点观察。",
      zone: "CN-HZ / 沙箱区",
      health: "healthy",
      owners: ["赵骁", "苏默"],
      projectCount: 7,
      throughput: 920,
      successRate: 0.99,
      tags: ["沙箱", "影子", "实验"],
      focus: "实验结果可以直接回灌到 Atlas Core",
    },
    {
      id: "harbor-risk",
      name: "Harbor 风险区",
      description: "承接高风险变更的多阶段复核与封板。",
      zone: "CN-BJ / 风险区",
      health: "critical",
      owners: ["陈杉", "高澈"],
      projectCount: 5,
      throughput: 410,
      successRate: 0.88,
      tags: ["风险", "评审", "发布"],
      focus: "昨夜回放失败后仍有封板残留",
    },
    {
      id: "night-shift",
      name: "Night Shift 夜班区",
      description: "夜间批处理与延迟队列清算工作区。",
      zone: "CN-SZ / 批处理区",
      health: "idle",
      owners: ["许默"],
      projectCount: 4,
      throughput: 260,
      successRate: 0.93,
      tags: ["批处理", "夜间", "清理"],
      focus: "当前窗口内无活跃负载",
    },
  ],
  runs: [
    {
      id: "run-9132",
      workspaceId: "atlas-core",
      title: "Atlas 夜间提案压缩",
      summary: "重新聚合昨日增量提案并触发审批串行回放。",
      trigger: "调度 / 30 分钟",
      status: "running",
      startedAt: "2026-04-20T11:24:00.000Z",
      updatedAt: "2026-04-20T11:58:00.000Z",
      progress: 0.72,
      operator: "atlas 调度器",
      changeId: "chg-184",
      stages: [
        {
          id: "collect",
          label: "收集",
          status: "completed",
          durationMs: 9 * 60_000,
          summary: "汇总 12 个项目的提案变更。",
        },
        {
          id: "review",
          label: "评审",
          status: "running",
          durationMs: 14 * 60_000,
          summary: "等待 Harbor Risk 人工复核返回。",
        },
        {
          id: "publish",
          label: "发布",
          status: "queued",
          durationMs: 0,
          summary: "审批通过后写回控制台与通知总线。",
        },
      ],
      logs: [
        "[11:24:02] queue accepted run-9132",
        "[11:31:18] collected 48 artifacts from Atlas Core",
        "[11:38:40] handed review bundle to Harbor Risk",
      ],
    },
    {
      id: "run-9128",
      workspaceId: "relay-labs",
      title: "影子发布拓扑镜像",
      summary: "验证新角色拓扑在影子工作区中的边连接关系。",
      trigger: "manual / designer",
      status: "completed",
      startedAt: "2026-04-20T09:10:00.000Z",
      finishedAt: "2026-04-20T09:44:00.000Z",
      updatedAt: "2026-04-20T09:44:00.000Z",
      progress: 1,
      operator: "relay 设计者",
      stages: [
        {
          id: "snapshot",
          label: "快照",
          status: "completed",
          durationMs: 6 * 60_000,
          summary: "导出实验拓扑快照。",
        },
        {
          id: "simulate",
          label: "模拟",
          status: "completed",
          durationMs: 18 * 60_000,
          summary: "模拟 4 条链路的并发回写。",
        },
        {
          id: "report",
          label: "报告",
          status: "completed",
          durationMs: 10 * 60_000,
          summary: "生成影子对比报告。",
        },
      ],
      logs: [
        "[09:10:11] snapshot saved",
        "[09:25:53] simulation completed without drift",
        "[09:44:07] report published to Relay Labs",
      ],
    },
    {
      id: "run-9124",
      workspaceId: "harbor-risk",
      title: "风险冻结回放",
      summary: "重新执行高风险封板的历史记录，检查回滚窗口。",
      trigger: "回放 / 事故处理",
      status: "failed",
      startedAt: "2026-04-20T07:42:00.000Z",
      finishedAt: "2026-04-20T08:11:00.000Z",
      updatedAt: "2026-04-20T08:11:00.000Z",
      progress: 0.58,
      operator: "harbor 运维",
      changeId: "chg-181",
      stages: [
        {
          id: "freeze",
          label: "冻结",
          status: "completed",
          durationMs: 8 * 60_000,
          summary: "封板成功，锁住待发布工单。",
        },
        {
          id: "audit",
          label: "审计",
          status: "failed",
          durationMs: 13 * 60_000,
          summary: "审计签名链返回校验不一致。",
        },
      ],
      logs: [
        "[07:42:09] freeze window locked",
        "[07:53:40] audit drift detected on edge release->audit",
        "[08:11:12] run aborted by policy gate",
      ],
    },
    {
      id: "run-9117",
      workspaceId: "night-shift",
      title: "夜间保留清理",
      summary: "等待下一批次窗口，清理过期运行日志与残留临时件。",
      trigger: "调度 / 夜间",
      status: "queued",
      startedAt: "2026-04-20T13:00:00.000Z",
      updatedAt: "2026-04-20T11:40:00.000Z",
      progress: 0.08,
      operator: "night-shift 调度器",
      stages: [
        {
          id: "prepare",
          label: "准备",
          status: "queued",
          durationMs: 0,
          summary: "等待低流量窗口。",
        },
      ],
      logs: ["[11:40:00] retention sweep parked until traffic drops"],
    },
  ],
  changes: [
    {
      id: "chg-184",
      workspaceId: "atlas-core",
      title: "队列交接压缩",
      summary: "压缩审批阶段与发布阶段之间的队列切换时间。",
      status: "review",
      owner: "张薇",
      reviewers: ["陈杉", "高澈"],
      risk: "medium",
      updatedAt: "2026-04-20T11:52:00.000Z",
      systems: ["规划", "评审", "发布"],
      checklist: ["回放链路回归", "审批超时门限检查", "通知扇出验证"],
      relatedRunIds: ["run-9132"],
      timeline: [
        {
          id: "opened",
          label: "已打开",
          at: "2026-04-20T10:32:00.000Z",
          note: "由 Atlas Core 从压测结果创建。",
        },
        {
          id: "review",
          label: "评审中",
          at: "2026-04-20T11:06:00.000Z",
          note: "Harbor Risk 请求补充边界说明。",
        },
      ],
    },
    {
      id: "chg-183",
      workspaceId: "relay-labs",
      title: "拓扑图例刷新",
      summary: "重做角色图例与节点色阶，使异常节点更显眼。",
      status: "approved",
      owner: "赵骁",
      reviewers: ["苏默"],
      risk: "low",
      updatedAt: "2026-04-20T09:36:00.000Z",
      systems: ["拓扑", "总览"],
      checklist: ["图例一致性", "暗背景对比度", "截图回归"],
      relatedRunIds: ["run-9128"],
      timeline: [
        {
          id: "opened",
          label: "已打开",
          at: "2026-04-20T08:58:00.000Z",
          note: "由 Relay Labs 主动发起。",
        },
        {
          id: "approved",
          label: "已批准",
          at: "2026-04-20T09:36:00.000Z",
          note: "通过设计与控制台验收。",
        },
      ],
    },
    {
      id: "chg-181",
      workspaceId: "harbor-risk",
      title: "冻结回放回滚保护",
      summary: "为回放失败场景补充回滚锁与审计保护。",
      status: "blocked",
      owner: "陈杉",
      reviewers: ["张薇", "高澈"],
      risk: "high",
      updatedAt: "2026-04-20T08:18:00.000Z",
      systems: ["审计", "发布", "保护"],
      checklist: ["回滚窗口互斥", "审计签名补录", "失败告警验证"],
      relatedRunIds: ["run-9124"],
      timeline: [
        {
          id: "opened",
          label: "已打开",
          at: "2026-04-20T07:26:00.000Z",
          note: "由事故处理流程直接创建。",
        },
        {
          id: "blocked",
          label: "已阻断",
          at: "2026-04-20T08:18:00.000Z",
          note: "审计签名不一致，禁止继续发布。",
        },
      ],
    },
    {
      id: "chg-177",
      workspaceId: "night-shift",
      title: "保留策略演练兜底",
      summary: "给夜间清理加上 dry-run 兜底开关。",
      status: "merged",
      owner: "许默",
      reviewers: ["赵骁"],
      risk: "low",
      updatedAt: "2026-04-19T22:14:00.000Z",
      systems: ["保留策略", "调度"],
      checklist: ["夜间任务回归", "日志抽样", "数据保留策略确认"],
      relatedRunIds: [],
      timeline: [
        {
          id: "merged",
          label: "已合并",
          at: "2026-04-19T22:14:00.000Z",
          note: "已合入夜间批处理分支。",
        },
      ],
    },
    {
      id: "chg-172",
      workspaceId: "atlas-core",
      title: "评审影子泳道",
      summary: "在主工作区旁路挂一条 reviewer 影子泳道。",
      status: "draft",
      owner: "徐澈",
      reviewers: ["张薇"],
      risk: "medium",
      updatedAt: "2026-04-19T18:20:00.000Z",
      systems: ["评审", "时间线"],
      checklist: ["泳道布局草图", "回放指标定义", "热节点标注"],
      relatedRunIds: [],
      timeline: [
        {
          id: "draft",
          label: "草稿",
          at: "2026-04-19T18:20:00.000Z",
          note: "等待进一步拆分实现范围。",
        },
      ],
    },
  ],
  topology: {
    scopeLabel: "执行网络 / 4 个工作区",
    roles: [
      {
        id: "intake",
        label: "接入",
        kind: "human",
        status: "healthy",
        members: ["张薇", "赵骁"],
      },
      {
        id: "planner",
        label: "规划",
        kind: "system",
        status: "healthy",
        members: ["atlas-planner", "relay-shadow", "batch-coordinator"],
      },
      {
        id: "review",
        label: "评审",
        kind: "human",
        status: "warning",
        members: ["陈杉", "高澈"],
      },
      {
        id: "executor",
        label: "执行",
        kind: "system",
        status: "healthy",
        members: ["publisher", "release-bot", "retention-bot"],
      },
      {
        id: "audit",
        label: "审计",
        kind: "system",
        status: "warning",
        members: ["audit-1", "audit-2"],
      },
      {
        id: "release",
        label: "发布",
        kind: "human",
        status: "healthy",
        members: ["许默"],
      },
    ],
    links: [
      { from: "intake", to: "planner", weight: "primary" },
      { from: "planner", to: "review", weight: "primary" },
      { from: "review", to: "executor", weight: "primary" },
      { from: "executor", to: "audit", weight: "secondary" },
      { from: "audit", to: "release", weight: "primary" },
    ],
  },
  settings: [
    {
      id: "runtime",
      title: "运行泳道",
      summary: "定义工作区在控制台中的执行节奏与串并行边界。",
      items: [
        {
          id: "refresh-window",
          label: "刷新窗口",
          value: "30 秒服务端轮询 / 本地局部更新",
          description: "服务端路由每 30 秒可重取，客户端只更新运行中局部。",
          mode: "managed",
        },
        {
          id: "queue-threshold",
          label: "队列阈值",
          value: "8 分钟预警 / 15 分钟严重",
          description: "超过阈值时将工作区健康度降级并打亮拓扑热点。",
          mode: "managed",
        },
      ],
    },
    {
      id: "approvals",
      title: "审批策略",
      summary: "影响变更看板与运行详情中审批阶段的可视化语义。",
      items: [
        {
          id: "shadow-reviewers",
          label: "影子评审人",
          value: "已在 Atlas 核心区启用",
          description: "允许在主审批之外接入一条影子复核泳道。",
          mode: "hybrid",
        },
        {
          id: "freeze-guard",
          label: "冻结保护",
          value: "要求审计一致性",
          description: "风险回放类变更必须通过审计签名一致性检查。",
          mode: "managed",
        },
      ],
    },
    {
      id: "retention",
      title: "保留策略",
      summary: "围绕夜间批处理和回放历史的保留策略骨架。",
      items: [
        {
          id: "run-history",
          label: "运行历史",
          value: "45 天",
          description: "运行详情页中超过保留期的日志将只展示摘要。",
          mode: "managed",
        },
        {
          id: "dry-run",
          label: "演练兜底",
          value: "已在 Night Shift 夜班区启用",
          description: "夜间清理默认先 dry-run，再允许人工放行。",
          mode: "draft",
        },
      ],
    },
  ],
};

export async function getDemoConsoleData(): Promise<DemoConsoleData> {
  return demoConsoleData;
}
